### ISSUE TITLE
'IGV Browser not ready'

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv-jupyter#23] opened 2019-02-14 22:11 UTC
Hi Jim,

I'm attempting to run igv.js-jupyter in a FireCloud Jupyter Notebook. I'm using the example notebooks you provide and I get the 'IGV Browser not ready' message that does not resolve over time. Is there something I should be doing to get past this?

Here are my specs:
![screenshot 2019-02-14 17 10 27](https://user-images.githubusercontent.com/11543866/52820959-75faeb80-307b-11e9-91ad-b1590e22f38e.png)

Thank you,
Soo Hee

**Comment by jrobinso** [comment] 2019-02-14 22:25
Did you install and enable the nbextension?  What are the steps you used to
install?

**Comment by sooheelee** [comment] 2019-02-15 16:29
I used `pip install igv`.

**Comment by jrobinso** [comment] 2019-02-15 16:38
On the firecloud server?  That should be enough but you might have to enable the extensions

jupyter nbextension install --py igv
jupyter nbextension enable --py igv

I'm actually a bit confused myself on the process for installing an extension on a share Jupyter server.  @tmtabor should know,  Thorin can you comment?    The symptom Soo Hee is seeing leads me to believe the extension is not installed.   @sooheelee Can you describe the Firecloud Jupyter setup a little,  is it a shared server,  or does the server and client both run on your machine?

**Comment by sooheelee** [comment] 2019-02-15 16:53
I'm using the Jupyter Notebooks _tab_ of FireCloud, which allows you to run a notebook on a standalone compute engine instance, specifically Dataproc. I just noticed https://github.com/igvteam/igv.js-jupyter/pull/21, but this was merged 26 days ago and the last release is from 28 days ago. Currently, here is what I'm seeing in the notebook:

![screenshot 2019-02-15 11 53 12](https://user-images.githubusercontent.com/11543866/52871543-4817b480-3118-11e9-8b13-db7e71bfc1c8.png)

**Comment by sooheelee** [comment] 2019-02-15 16:55
What I ultimately need is to be able to visualize BigWig files in a FireCloud workspace, towards illustrating the GATK gCNV workflow.

**Comment by sooheelee** [comment] 2019-02-15 17:01
I am trying to debug and really appreciate the help. Towards debugging I found https://github.com/Calysto/notebook-extensions/issues/4 and if I `jupyter nbextension list`, I see:

![screenshot 2019-02-15 11 59 35](https://user-images.githubusercontent.com/11543866/52871988-5d411300-3119-11e9-836f-b3fdf70d5ef4.png)

Not sure if helpful but I thought I'd share.

**Comment by jrobinso** [comment] 2019-02-15 17:13
Did you pip install this on the Firecloud Jupyter server,  or on your client machine, or both?

**Comment by sooheelee** [comment] 2019-02-15 17:41
My client machine, a Google Compute Engine instance. I have a script that `pip install igv` plus GATK when the instance is created.

**Comment by jrobinso** [comment] 2019-02-15 17:44
That won't be enough,  it needs to be installed on the server.   Having the admin run pip install igv on the server might be enough, but let's wait for @tmtabor to respond before trying that.

**Comment by sooheelee** [comment] 2019-02-15 17:45
Ok. Here's some more information on the Jupyter Notebook (aka Leonardo) - FireCloud relationship: https://github.com/DataBiosphere/leonardo

**Comment by jrobinso** [comment] 2019-02-15 17:53
Who administers this?  IGV is a Jupyter extension, with python (server) and javascript (client) parts.   The admin will definitely need to be involved in the installation and should be looped into this conversation.

**Comment by sooheelee** [comment] 2019-02-15 17:56
Yes, I have asked @MatthewBemis and @kyuksel to weigh in.

**Comment by tmtabor** [comment] 2019-02-15 18:26
I have seen this sort of error before. It usually happens when Jupyter has been installed as root, but you're trying to install a Jupyter extension from a user account.

What happens is that when you install Jupyter, it creates the directory `/usr/local/share/nbextensions/` to contain its extensions. But if you're installing Jupyter as root, user accounts aren't going to have write permission to that directory. So when you try to install an extension there, it fails. ([Seen in this screenshot.](https://github.com/igvteam/igv.js-jupyter/issues/23#issuecomment-464120769))

The real fix is to either install the extension as root, reinstall Jupyter from your user account or make `/usr/local/share/nbextensions/` writable. I don't know FireCloud's particular setup, but I suspect this will require the system administrator.

**Comment by rtitle** [comment] 2019-02-15 18:45
@tmtabor @sooheelee would this work?
```
!pip3 install igv
!jupyter nbextension install --py igv --user
!jupyter nbextension enable --py igv --user
```
I think this should install the extensions in user space?

Otherwise, Terra notebooks support plugging in "user scripts" which allow you to install/run things as root when the notebook server launches. That also might be a path forward here.

**Comment by sooheelee** [comment] 2019-02-15 18:53
Thanks @tmtabor for the insight and @rtitle for a potential solution. I tried adding `--user` but I still get some Xs when I `jupyter nbextension list`:

![screenshot 2019-02-15 13 50 58](https://user-images.githubusercontent.com/11543866/52877728-d1cf7e00-3128-11e9-9e73-593067d0f4c1.png)

**Comment by sooheelee** [comment] 2019-02-15 19:02
I didn't realize the `custom script` is run with root privileges, so I am waiting for a new cluster to form where I've added the extension-install to the script.

**Comment by jrobinso** [comment] 2019-02-15 19:05
@sooheelee @rtitle I think this extension will be of broad interest to Firecloud users.   Could it be installed as part of the image for everyone?

**Comment by sooheelee** [comment] 2019-02-15 19:16
Well, even with the custom script containing:
```
set -e
pip install igv
jupyter nbextension install --py igv
jupyter nbextension enable --py igv
```

on a fresh cluster, I get the same errors I show in the last screencapture above (_https://github.com/igvteam/igv.js-jupyter/issues/23#issuecomment-464159151_).

What can I try next? Really appreciate all the support here. Definitely @jrobinso @rtitle I think the igv.js-jupyter extension is of great interest to researchers.

**Comment by tmtabor** [comment] 2019-02-15 19:28
In theory, the X's for _nbextensions_configurator_ shouldn't affect igv since that's a [different nbextension](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator). 

But you can probably fix them by installing it as root (or with `--user`) as well.

**Comment by rtitle** [comment] 2019-02-15 19:39
Yeah I'm not sure those red X's matter. I did the following as root:
```
pip3 install igv
jupyter nbextension install --py igv
jupyter nbextension enable --py igv
```
and this in a notebook:
![image](https://user-images.githubusercontent.com/5368863/52880204-56bd9600-312f-11e9-80e0-6dfd5e42d401.png)

No cell errors but I do see errors in browser console:
![image](https://user-images.githubusercontent.com/5368863/52880265-7eacf980-312f-11e9-9e07-01e72b9880b8.png)

Any idea what this means?

**Comment by rtitle** [comment] 2019-02-15 19:42
Is there a serverextension that needs to be installed in addition to a nbextension?

**Comment by rtitle** [comment] 2019-02-15 19:46
> I think this extension will be of broad interest to Firecloud users. Could it be installed as part of the image for everyone?

First we need to get it working. :) But yeah then we consider installing it by default.

**Comment by jrobinso** [comment] 2019-02-15 20:02
@rtitle this is both a server and nbextension,  but pip install should install both.      I'll see if I can reproduce this and get back to you.  Stay tuned.

**Comment by jrobinso** [comment] 2019-02-15 23:41
@sooheelee @rtitle @tmtabor 
OK, Helga was able to reproduce the  "IGVBrowser not ready" with the "igvcomm not in registry error", but explicitly installing the nbextensions resolved it.  @helgathorv correct me if I'm wrong here.  The explicit install/enable should not have been neccessary, we followed instructions [here]( https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html), but obviously that wasn't working for everyone.  So I've removed the auto-install and pushed a new version,  0.9.5, to pipy along with updated instructions.   I tested with a fresh conda virtual environment,  I'm going to list everything I did below for completeness but creation of the virtual environment would not apply in your case.   However, if it still doesn't work with firecloud could you try a fresh environment as below?

* Create the virtual environment

```
conda create -n test python=3.7.1
conda activate test
conda install pip
conda install jupyter
```

* Install IGV  -- note that you would not include the --sys-prefix flag if not in a virtual environment

```
pip install igv
jupyter serverextension enable --py igv --sys-prefix
jupyter nbextension install --py igv --sys-prefix
jupyter nbextension enable --py igv --sys-prefix
```

* Run the notebook

```
jupyter notebook
```

**Comment by sooheelee** [comment] 2019-02-16 14:35
Thanks, @jrobinso @helgathorv for these instructions. They work great on my laptop. It's a geat feeling to be able to interact with the data via the embedding. I hope @rtitle can enable this functionality on FireCloud Notebooks soon. 

<img width="969" alt="screenshot 2019-02-16 09 33 14" src="https://user-images.githubusercontent.com/11543866/52901198-1cef9c80-31ce-11e9-8c6d-18e7b3fb1b23.png">

**Comment by sooheelee** [comment] 2019-02-20 15:21
### Update and follow-up question 
With permission, I've moved my secondary analyses off of FireCloud for now. I need **a heatmap visualization of germline copy-number variants** derived from WGS samples, where the heatmap coloring corresponds to copy number. Yesterday I tested out three file formats towards visualization. I am hoping you can tell me if I've missed some way of getting to where I need in igv.js-jupyter (IGV). I'd really appreciate your insight. 

![screenshot 2019-02-20 09 45 33](https://user-images.githubusercontent.com/11543866/53099720-56891600-34f4-11e9-8e54-633c12a0bbfc.png)

1. VCFs of structural variants, where the POS field indicates the start of a CNV and the INFO field's `END=` annotation indicates the end of the same CNV event. Depending on the source of the callset, the extent of copy gain/loss is either denoted in the ALT field, e.g. with `<CN0>` or in a FORMAT level annotation, e.g. `CN` annotation is 0 in the sample field. 
    - IGV marks the starting POS but does not extend the variant representation to the END postion. I know block-representation is possible in desktop-IGV for _GVCF_ visualization. I tried changing the file-extension to `.g.vcf` but this did not change the visualization.
    - IGV coloring is based on GT. Need to color by CN state.
    - Feature visibility is independent of zoom-level, which is great.
2. SEG file where segment mean reflects copy number, e.g. 2 is diploid normal.
    - IGV fully represents the start and end of the variant and colors appropriately (blue-white-red)!
    - Feature visibility is dependent on zoom-level. Features are often not visible until zoomed in considerably, making us dependent on also loading the VCF. 
3. BW bigwig file, which is performant for the size of the data (24 WGS samples). I had been using this format and desktop-IGV's heatmap coloring capability so far, based on the two different result formats of GATK4 gCNV. One of the formats gives a feature for every bin of data collected, e.g. every 1000bp of a WGS dataset.
    - IGV displays data as a graph, much like a histogram, which is useful.
    - Cannot convert to heatmap format like in desktop-IGV. Is this possible, and how do I go about it?

I would really like to be able to compare heatmaps that have full feature-visibility even at full-contig view levels. Thank you @jrobinso @tmtabor.

**Comment by jrobinso** [comment] 2019-02-21 06:48
Seg files do not have visibility window restrictions, they even work at whole genome, so I'm not sure what is going on here.  Possibly the segments get too small to see.  Please open an issue in igv.js  on this issue and attach an example seg file that reproduces the problem.   I'm closing this issue since the "browser not ready" problem is resolved.

**Closed by jrobinso** 2019-02-21 06:48 UTC

**Comment by sooheelee** [comment] 2019-02-22 17:10
I suspect the diploid segments (in white) are given equal visibility as the non-diploid segments of interest (in blue and in red). I will see if removing CN=2 segments allows for better representation at the contig level before I open a new issue. Would it be okay for me to open an issue requesting heatmap representation of bigwigs in igv.js-jupyter?

**Comment by jrobinso** [comment] 2019-02-22 17:33
@sooheelee The request should be to igv.js,  this is not about jupyter,  but that is not likely to get prioritized anytime soon.

**Comment by HBegali** [comment] 2019-07-29 12:42
@sooheelee 
@jrobinso 
Thanks for ur comments
